CREATE DATABASE Wheelzy;
GO

USE Wheelzy;
GO

-- MAKE TABLE CREATION
CREATE TABLE Make (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
);
GO


-- MODEL TABLE CREATION
CREATE TABLE Model (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	MakeId INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	FOREIGN KEY (MakeId) REFERENCES Make(Id)
);
GO


-- SUBMODEL TABLE CREATION
CREATE TABLE Submodel (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ModelId INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	FOREIGN KEY (ModelId) REFERENCES Model(Id)
);
GO


-- CUSTOMER TABLE CREATION
CREATE TABLE Customer (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL
);
GO


-- ZIP CODE TABLE CREATION
CREATE TABLE ZipCode (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Code NVARCHAR(5) NOT NULL
);
GO


-- CAR TABLE CREATION
CREATE TABLE Car (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CustomerId INT NOT NULL,
	[Year] NVARCHAR(4) NOT NULL,
	MakeId INT NOT NULL,
	ModelId INT NOT NULL,
	SubmodelId INT NOT NULL,
	ZipCodeId INT NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES Customer(Id),
	FOREIGN KEY (MakeId) REFERENCES Make(Id),
	FOREIGN KEY (ModelId) REFERENCES Model(Id),
	FOREIGN KEY (SubModelId) REFERENCES SubModel(Id),
	FOREIGN KEY (ZipCodeId) REFERENCES ZipCode(Id),
);
GO


-- BUYER TABLE CREATION
CREATE TABLE Buyer (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL
);
GO


-- ZIPCODE TO BUYER TABLE CREATION
CREATE TABLE ZipCode_Buyer (
	ZipCodeId INT NOT NULL,
	BuyerId INT NOT NULL,
	FOREIGN KEY (ZipCodeId) REFERENCES ZipCode(Id),
	FOREIGN KEY (BuyerId) REFERENCES Buyer(Id),
	PRIMARY KEY (ZipCodeId, BuyerId)
);
GO


-- STATUS TABLE CREATION
CREATE TABLE [Status] (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	HasMandatoryDate BIT NOT NULL DEFAULT 0
);
GO


-- CAR QUOTE TABLE CREATION
CREATE TABLE CarQuote (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CarId INT NOT NULL,
	BuyerId INT NOT NULL,
	StatusId INT NOT NULL,
	IsCurrent BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (CarId) REFERENCES Car(Id),
	FOREIGN KEY (BuyerId) REFERENCES Buyer(Id),
	FOREIGN KEY (StatusId) REFERENCES [Status](Id)
);
GO

-- UNIQUE INDEX "ISCURRENT" BY CAR QUOTE
CREATE UNIQUE INDEX UI_CarQuote_CarId_IsCurrent
ON CarQuote (CarId)
WHERE IsCurrent = 1;
GO


-- STATUS HISTORY TABLE CREATION
CREATE TABLE StatusHistory (
	CarQuoteId INT NOT NULL,
	StatusId INT NOT NULL,
	[Date] DATETIME NULL,
	ChangedBy NVARCHAR(50) NULL,
	FOREIGN KEY (CarQuoteId) REFERENCES CarQuote(Id),
	FOREIGN KEY (StatusId) REFERENCES [Status](Id),
	PRIMARY KEY (CarQuoteId, StatusId)
);
GO

